/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TopicSlugRouteImport } from "./routes/topic.$slug";
import { Route as ApiSuggestionsRouteImport } from "./routes/api/suggestions";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as ApiExplainPromptRouteImport } from "./routes/api/explain-prompt";
import { Route as TopicSlugPromptPromptIdRouteImport } from "./routes/topic.$slug.prompt.$promptId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: "/topic/$slug",
  path: "/topic/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: "/api/suggestions",
  path: "/api/suggestions",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiExplainPromptRoute = ApiExplainPromptRouteImport.update({
  id: "/api/explain-prompt",
  path: "/api/explain-prompt",
  getParentRoute: () => rootRouteImport,
} as any);
const TopicSlugPromptPromptIdRoute = TopicSlugPromptPromptIdRouteImport.update({
  id: "/prompt/$promptId",
  path: "/prompt/$promptId",
  getParentRoute: () => TopicSlugRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/explain-prompt": typeof ApiExplainPromptRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/suggestions": typeof ApiSuggestionsRoute;
  "/topic/$slug": typeof TopicSlugRouteWithChildren;
  "/topic/$slug/prompt/$promptId": typeof TopicSlugPromptPromptIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/explain-prompt": typeof ApiExplainPromptRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/suggestions": typeof ApiSuggestionsRoute;
  "/topic/$slug": typeof TopicSlugRouteWithChildren;
  "/topic/$slug/prompt/$promptId": typeof TopicSlugPromptPromptIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/explain-prompt": typeof ApiExplainPromptRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/suggestions": typeof ApiSuggestionsRoute;
  "/topic/$slug": typeof TopicSlugRouteWithChildren;
  "/topic/$slug/prompt/$promptId": typeof TopicSlugPromptPromptIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/api/explain-prompt"
    | "/api/health"
    | "/api/suggestions"
    | "/topic/$slug"
    | "/topic/$slug/prompt/$promptId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/api/explain-prompt"
    | "/api/health"
    | "/api/suggestions"
    | "/topic/$slug"
    | "/topic/$slug/prompt/$promptId";
  id:
    | "__root__"
    | "/"
    | "/api/explain-prompt"
    | "/api/health"
    | "/api/suggestions"
    | "/topic/$slug"
    | "/topic/$slug/prompt/$promptId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiExplainPromptRoute: typeof ApiExplainPromptRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute;
  TopicSlugRoute: typeof TopicSlugRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/topic/$slug": {
      id: "/topic/$slug";
      path: "/topic/$slug";
      fullPath: "/topic/$slug";
      preLoaderRoute: typeof TopicSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/suggestions": {
      id: "/api/suggestions";
      path: "/api/suggestions";
      fullPath: "/api/suggestions";
      preLoaderRoute: typeof ApiSuggestionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/explain-prompt": {
      id: "/api/explain-prompt";
      path: "/api/explain-prompt";
      fullPath: "/api/explain-prompt";
      preLoaderRoute: typeof ApiExplainPromptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/topic/$slug/prompt/$promptId": {
      id: "/topic/$slug/prompt/$promptId";
      path: "/prompt/$promptId";
      fullPath: "/topic/$slug/prompt/$promptId";
      preLoaderRoute: typeof TopicSlugPromptPromptIdRouteImport;
      parentRoute: typeof TopicSlugRoute;
    };
  }
}

interface TopicSlugRouteChildren {
  TopicSlugPromptPromptIdRoute: typeof TopicSlugPromptPromptIdRoute;
}

const TopicSlugRouteChildren: TopicSlugRouteChildren = {
  TopicSlugPromptPromptIdRoute: TopicSlugPromptPromptIdRoute,
};

const TopicSlugRouteWithChildren = TopicSlugRoute._addFileChildren(TopicSlugRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExplainPromptRoute: ApiExplainPromptRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
  TopicSlugRoute: TopicSlugRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
